/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as authLayoutAuthSignUpRouteImport } from './routes/(auth)/_layout.auth/sign-up'
import { Route as authLayoutAuthSignInRouteImport } from './routes/(auth)/_layout.auth/sign-in'
import { Route as authLayoutAuthResetPasswordRouteImport } from './routes/(auth)/_layout.auth/reset-password'
import { Route as authLayoutAuthResendOtpPageRouteImport } from './routes/(auth)/_layout.auth/resend-otp-page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutAuthSignUpRoute = authLayoutAuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutAuthSignInRoute = authLayoutAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutAuthResetPasswordRoute =
  authLayoutAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutAuthResendOtpPageRoute =
  authLayoutAuthResendOtpPageRouteImport.update({
    id: '/auth/resend-otp-page',
    path: '/auth/resend-otp-page',
    getParentRoute: () => authLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/resend-otp-page': typeof authLayoutAuthResendOtpPageRoute
  '/auth/reset-password': typeof authLayoutAuthResetPasswordRoute
  '/auth/sign-in': typeof authLayoutAuthSignInRoute
  '/auth/sign-up': typeof authLayoutAuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/resend-otp-page': typeof authLayoutAuthResendOtpPageRoute
  '/auth/reset-password': typeof authLayoutAuthResetPasswordRoute
  '/auth/sign-in': typeof authLayoutAuthSignInRoute
  '/auth/sign-up': typeof authLayoutAuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(auth)/_layout/auth/resend-otp-page': typeof authLayoutAuthResendOtpPageRoute
  '/(auth)/_layout/auth/reset-password': typeof authLayoutAuthResetPasswordRoute
  '/(auth)/_layout/auth/sign-in': typeof authLayoutAuthSignInRoute
  '/(auth)/_layout/auth/sign-up': typeof authLayoutAuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/resend-otp-page'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/resend-otp-page'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_layout'
    | '/(auth)/_layout/auth/resend-otp-page'
    | '/(auth)/_layout/auth/reset-password'
    | '/(auth)/_layout/auth/sign-in'
    | '/(auth)/_layout/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/auth/sign-up': {
      id: '/(auth)/_layout/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof authLayoutAuthSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/auth/sign-in': {
      id: '/(auth)/_layout/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof authLayoutAuthSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/auth/reset-password': {
      id: '/(auth)/_layout/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authLayoutAuthResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/auth/resend-otp-page': {
      id: '/(auth)/_layout/auth/resend-otp-page'
      path: '/auth/resend-otp-page'
      fullPath: '/auth/resend-otp-page'
      preLoaderRoute: typeof authLayoutAuthResendOtpPageRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutAuthResendOtpPageRoute: typeof authLayoutAuthResendOtpPageRoute
  authLayoutAuthResetPasswordRoute: typeof authLayoutAuthResetPasswordRoute
  authLayoutAuthSignInRoute: typeof authLayoutAuthSignInRoute
  authLayoutAuthSignUpRoute: typeof authLayoutAuthSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutAuthResendOtpPageRoute: authLayoutAuthResendOtpPageRoute,
  authLayoutAuthResetPasswordRoute: authLayoutAuthResetPasswordRoute,
  authLayoutAuthSignInRoute: authLayoutAuthSignInRoute,
  authLayoutAuthSignUpRoute: authLayoutAuthSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
